version: '3'
services:
  web:
    build: ./build/web
    ports:
      - "8080:8080"
    environment:
      - GO_ENV=local
      - TZ=Asia/Tokyo

  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname
    ports:
      - "5432:5432"
